### ISSUE TITLE
[LISTING] categories menu

### ISSUE THREAD

**Issue by jberlioz** [3cixty/web-client-sample#13]
![categories](https://cloud.githubusercontent.com/assets/16953452/15715960/c674245c-2820-11e6-9d08-a326666cb07e.JPG)

The categorie menu must be designed like this (with a graphical link to its icon when opened) : 

![categories-mockup](https://cloud.githubusercontent.com/assets/16953452/15715970/ce64bfaa-2820-11e6-828c-d730e2b3638e.JPG)

**Comment by rtroncy** [comment]
Your issue should be posted at https://github.com/3cixty/exploration ! Closing this issue
