### ISSUE TITLE
[TABS / LISTING / NODE] Tools icons integration 

### ISSUE THREAD

**Issue by jberlioz** [3cixty/web-client-sample#2]
![tools-icon-in-bar](https://cloud.githubusercontent.com/assets/16953452/15712180/a7666548-2811-11e6-8975-78082c24f806.JPG)

These integration are missings : 
- 2 icons tools on each side of a tab
- 3 icons in each request, below the tab
- 2 icons in each node

**Comment by rtroncy** [comment]
There is a misunderstanding of what this repository is about ... a old and dummy repository (2 years old !!!), not private (seriously !!!) made to explain in 2014 how third party apps in a challenge should authenticate to 3cixty. The fact that there is no issues here should have alerted you. Your issue should be posted at https://github.com/3cixty/exploration ! Closing this issue and all the others.
