### ISSUE TITLE
[NODE] pop up opening bug 

### ISSUE THREAD

**Issue by jberlioz** [3cixty/web-client-sample#3]
![bug-popup](https://cloud.githubusercontent.com/assets/16953452/15712256/f688a9e2-2811-11e6-99ea-88ae577201a1.JPG)

There is a bug when opening a node while there are 2 columns. If you open it from the left column, the popup is displayed under the right column.

**Comment by rtroncy** [comment]
Your issue should be posted at https://github.com/3cixty/exploration ! Closing this issue.
