### ISSUE TITLE
[NODE] menu integration

### ISSUE THREAD

**Issue by jberlioz** [3cixty/web-client-sample#4]
![currentwebapp-node-item](https://cloud.githubusercontent.com/assets/16953452/15712543/f6b2a05c-2812-11e6-9e55-918d1649830f.JPG)

The contextual menu in a node is not integrated yet. 

The dynamic layer with icons must be orange with a graphical link to its icon (see below). 

![mockup-node-item](https://cloud.githubusercontent.com/assets/16953452/15712630/65f1828a-2813-11e6-9453-faa7c4af22e1.JPG)

**Comment by rtroncy** [comment]
Your issue should be posted at https://github.com/3cixty/exploration ! Closing this issue
