### ISSUE TITLE
[TAB] selected values

### ISSUE THREAD

**Issue by jberlioz** [3cixty/web-client-sample#5]
![current-selectedvalues](https://cloud.githubusercontent.com/assets/16953452/15712738/bff2c85c-2813-11e6-9f65-d8067bd50fdc.JPG)

Selected values in tabs are currently black whereas they should be white (see below) 

![selectedvalues](https://cloud.githubusercontent.com/assets/16953452/15712763/d66c69b2-2813-11e6-83d8-d1d48a317289.JPG)

**Comment by rtroncy** [comment]
Your issue should be posted at https://github.com/3cixty/exploration ! Closing this issue
