### ISSUE TITLE
[TABS] background design is missing 

### ISSUE THREAD

**Issue by jberlioz** [3cixty/web-client-sample#6]
![notwhitearrow](https://cloud.githubusercontent.com/assets/16953452/15712863/42d792f2-2814-11e6-83c1-243614f70eda.JPG)

The white arrow background is missing in each PE view : 

![whitearrow](https://cloud.githubusercontent.com/assets/16953452/15712908/70b429d8-2814-11e6-91c5-2c69f3406819.JPG)

So the first tab (all events or all places) must be smaller and on the end of the white background arrow

**Comment by rtroncy** [comment]
Your issue should be posted at https://github.com/3cixty/exploration ! Closing this issue
