### ISSUE TITLE
[TABS] Expand / minimize icon

### ISSUE THREAD

**Issue by jberlioz** [3cixty/web-client-sample#7]
On the right side, the icon is not really visible. 
So We should use this red circle background to the current button : 

![rond rouge](https://cloud.githubusercontent.com/assets/16953452/15713508/0263ee16-2817-11e6-8326-067318d18818.JPG)

In this red circle, the current icon must be colored in white. Then the whole button must be positionned on the end of the Header's arrow (fold or unfold). 

![positionrondrouge](https://cloud.githubusercontent.com/assets/16953452/15713538/200672b8-2817-11e6-8fc1-172fb4542f38.JPG)

**Comment by rtroncy** [comment]
Your issue should be posted at https://github.com/3cixty/exploration ! Closing this issue
