### ISSUE TITLE
[TAB] all event and places

### ISSUE THREAD

**Issue by jberlioz** [3cixty/web-client-sample#8]
The global "All event and places" tab on the top must be smaller like this : 

![mockupallevents](https://cloud.githubusercontent.com/assets/16953452/15713842/61bfa46c-2818-11e6-8c1d-1986616a2b61.JPG)

Then it must be positionned in the middle : 

![allevents-places](https://cloud.githubusercontent.com/assets/16953452/15713864/706a926a-2818-11e6-8eb8-a10e6c04210a.JPG)

If the "all events and places" is displayed alone, then it must be displayed with white background and icons as others like this : 

![allep-alone](https://cloud.githubusercontent.com/assets/16953452/15714682/c3abfc40-281b-11e6-9988-74f34eccb4b9.JPG)

The "explore Events" and "Explore Places" menu must be available by clicking on the filter icon with the same graphical integration with icons : 

![allep-alone-menu](https://cloud.githubusercontent.com/assets/16953452/15714790/414c8d54-281c-11e6-8cdd-290d9186e6df.JPG)

**Comment by rtroncy** [comment]
Your issue should be posted at https://github.com/3cixty/exploration ! Closing this issue
